---
:project: katello
:releases:
  :2.1:
    :redmine_version_id: 507
:repos:
  :katello:
    :branch: KATELLO-2.1
    :repo: https://github.com/Katello/katello.git
  :katello-installer:
    :branch: KATELLO-2.1
    :repo: https://github.com/Katello/katello-installer.git
  :hammer-cli-katello:
    :branch: 0.0.7
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello.org:
    :branch: KATELLO-2.1
    :repo: https://github.com/Katello/katello.org.git
  :katello-agent:
    :branch: KATELLO-2.1
    :repo: https://github.com/Katello/katello-agent.git
:ignores:
  - 7423
  - 8265
  - 7815
