---
:project: katello
:github_org: katello
:prior_releases:
:releases:
  :3.11.0:
    :redmine_version_id: 946
:code_name: Beautiful Disaster
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.11
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/1.21
    :repo: https://github.com/theforeman/foreman-packaging.git
  :katello-host-tools:
    :branch: 3.4.1
    :repo: https://github.com/Katello/katello-host-tools.git
  :puppet-foreman_proxy_content:
    :branch: 8.0.0
    :repo: https://github.com/theforeman/puppet-foreman_proxy_content
  :puppet-certs:
    :branch: 5.0.0
    :repo: https://github.com/theforeman/puppet-certs
  :hammer-cli-katello:
    :branch: 0.17.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
:ignores:
  - 24927 # katello-installer now foreman-installer
  - 25625 # katello-installer now foreman-installer
  - 25662 # katello-installer now foreman-installer
  - 25665 # katello-installer now foreman-installer
  - 25739 # puppet-certs, in 5.0.0
  - 25429 # duplicate
  - 24718 # duplicate
  - 25232 # resolved, no PR
:strict_keys: true
:gpg_key: '0A220E1C'
:mash_scripts:
 - katello-3.11-thirdparty-candlepin-rhel7
 - katello-3.11-rhel7
:tags:
  - name: katello-3.11-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.11-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.11-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.11-rhel7-override: null
    build_target: katello-3.11-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.11-rhel7-build:
        katello-3.11-rhel7-override: 0
        tfm-ror52-rhel7: 2
        foreman-plugins-1.21-rhel7-override: 3
        foreman-1.21-nonscl-rhel7: 4
        foreman-1.21-rhel7: 10
      katello-3.11-rhel7-override:
        katello-3.11-rhel7: 0
      katello-3.11-rhel7:
        katello-3.11-thirdparty-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
