---
:project: katello
:github_org: katello
:prior_releases:
  :3.12.2:
    :redmine_version_id: 1053
  :3.12.1:
    :redmine_version_id: 1031
  :3.12.0:
    :redmine_version_id: 993
:releases:
  :3.13.0:
    :redmine_version_id: 1021
:code_name: Baltic Porter
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.13
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/1.23
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.19.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :puppet-certs:
    :branch: 6.0.1
    :repo: https://github.com/theforeman/puppet-certs
  :katello-host-tools:
    :branch: 3.5.1
    :repo: https://github.com/Katello/katello-host-tools.git
:ignores:
:strict_keys: true
:gpg_key: 'D4BFEBD8'
:mash_scripts:
 - katello-3.13-thirdparty-candlepin-rhel7
 - katello-3.13-rhel7
:tags:
  - name: katello-3.13-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.13-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.13-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.13-rhel7-override: null
    build_target: katello-3.13-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.13-rhel7-build:
        katello-3.13-rhel7-override: 0
        foreman-rails-1.23-rhel7: 2
        foreman-plugins-1.23-rhel7-override: 3
        foreman-1.23-rhel7: 10
      katello-3.13-rhel7-override:
        katello-3.13-rhel7: 0
      katello-3.13-rhel7:
        katello-3.13-thirdparty-rhel7: 0
        foreman-1.23-nonscl-rhel7: 1
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
