---
:project: katello
:github_org: katello
:prior_releases: []
:releases:
  :3.15.0:
    :redmine_version_id: 1131
:code_name: Rocky Road
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.15
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/2.0
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.21.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.5.3
    :repo: https://github.com/Katello/katello-host-tools.git
:ignores:
:strict_keys: true
:gpg_key: 0579baee
:mash_scripts:
  - katello-3.15-rhel7
  - katello-3.15-thirdparty-candlepin-rhel7
  - katello-pulpcore-3.15-el7
:tags:
  - name: katello-3.15-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.15-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.15-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.15-rhel7-override: null
    build_target: katello-3.15-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.15-rhel7-build:
        katello-3.15-rhel7-override: 0
        foreman-plugins-2.0-rhel7-override: 3
        foreman-2.0-rhel7: 10
      katello-3.15-rhel7-override:
        katello-3.15-rhel7: 0
      katello-3.15-rhel7:
        katello-3.15-thirdparty-rhel7: 0
        foreman-2.0-nonscl-rhel7: 1
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
  - name: katello-pulpcore-3.15-el7
    based_off: katello-pulpcore-nightly-el7
    arches:
      - x86_64
    build_target: katello-pulpcore-3.15-el7-build
    build_package_group_source_tag: katello-pulpcore-nightly-el7-build
    external_repos:
      - centos7-os
      - centos7-updates
