---
:project: katello
:github_org: katello
:releases:
  :3.16.2: 
    :redmine_version_id: 1308
  :3.16.1.2:
    :redmine_version_id: 1313
  :3.16.1.1:
    :redmine_version_id: 1312
  :3.16.1:
    :redmine_version_id: 1226
  :3.16.0:
    :redmine_version_id: 1184
:prior_releases:
  :3.15.2:
    :redmine_version_id: 1238
  :3.15.3:
    :redmine_version_id: 1257
:code_name: Tasty Taiyaki
:mash_scripts:
  - katello-3.16-rhel7
  - katello-3.16-el8
  - katello-pulpcore-3.16-el7
  - katello-pulpcore-3.16-el8
  - katello-3.16-thirdparty-candlepin-rhel7
  - katello-candlepin-3.16-el8
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.16
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/2.1
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.22.2
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.5.4
    :repo: https://github.com/Katello/katello-host-tools.git
:ignores:
  - 28719 # Closed
  - 21508 # Fixed outside of Katello repo
  - 29435 # Fixed outside of Katello repo
  - 29449 # Fixed outside of Katello repo
  - 29436 # Fixed outside of Katello repo
  - 29340 # Closed
  - 28918 # Tracker
  - 28795 # Duplicate
  - 29603 # Fixed outside of Katello repo
  - 28968 # Tracker
  - 27501 # Already in branch
  - 28719 # Support issue
  - 29603 # Fixed outside of Katello repo
  - 30021 # Merged in a separate PR
  - 30088 # Fixed outside of Katello repo
  - 29312 # Tracker
  - 30283 # Already in branch
  - 30472 # Duplicate
:strict_keys: true
:gpg_key: B6F08CCF
:tags:
  - name: katello-3.16-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    build_target: katello-3.16-rhel7-build
    arches:
      - x86_64
  - name: katello-candlepin-3.16-el8
    based_off: katello-candlepin-nightly-el8
    build_target: katello-3.16-el8-build
    arches:
      - x86_64
  - name: katello-3.16-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.16-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.16-rhel7-override: null
    build_target: katello-3.16-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.16-rhel7-build:
        katello-3.16-rhel7-override: 0
        foreman-plugins-2.1-rhel7-override: 3
        foreman-2.1-rhel7: 10
      katello-3.16-rhel7-override:
        katello-3.16-rhel7: 0
      katello-3.16-rhel7:
        katello-3.16-thirdparty-rhel7: 0
        foreman-2.1-nonscl-rhel7: 1
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
  - name: katello-3.16-el8
    based_off: katello-nightly-el8
    helper_tags:
      katello-3.16-thirdparty-el8: katello-thirdparty-el8
      katello-3.16-el8-override: null
    build_target: katello-3.16-el8-build
    build_package_group_source_tag: katello-nightly-el8-build
    arches:
      - x86_64
    inherits:
      katello-3.16-el8-build:
        katello-3.16-el8-override: 0
        foreman-plugins-2.1-el8: 3
        foreman-2.1-el8: 5
      katello-3.16-el8-override:
        katello-3.16-el8: 0
      katello-3.16-el8:
        katello-3.16-thirdparty-el8: 0
    external_repos:
      - test-flat-el8
      - centos8-devel
      - puppetlabs-puppet6-rhel-8
  - name: katello-pulpcore-3.16-el7
    based_off: katello-pulpcore-nightly-el7
    helper_tags:
      katello-pulpcore-3.16-el7-override: null
    arches:
      - x86_64
    build_target: katello-pulpcore-3.16-el7-build
    inherits:
      katello-pulpcore-3.16-el7-build:
        katello-pulpcore-3.16-el7-override: 0
      katello-pulpcore-3.16-el7-override:
        katello-pulpcore-3.16-el7: 0
    build_package_group_source_tag: katello-pulpcore-nightly-el7-build
    external_repos:
      - centos7-os
      - centos7-updates
      - centos-sclo-rh-rhel-7
      - epel-7
  - name: katello-pulpcore-3.16-el8
    based_off: katello-pulpcore-nightly-el8
    helper_tags:
      katello-pulpcore-3.16-el8-override: null
    arches:
     - x86_64
    build_target: katello-pulpcore-3.16-el8-build
    inherits:
      katello-pulpcore-3.16-el8-build:
        katello-pulpcore-3.16-el8-override: 0
      katello-pulpcore-3.16-el8-override:
        katello-pulpcore-3.16-el8: 0
    build_package_group_source_tag: katello-pulpcore-nightly-el8-build
    external_repos:
      - centos8-baseos
      - centos8-appstream
      - centos8-powertools
      - centos8-devel
