---
:project: katello
:github_org: katello
:releases:
  :3.16.0:
    :redmine_version_id: 1184
:prior_releases: []
:code_name: Tasty Taiyaki
:mash_scripts:
  - katello-3.16-rhel7
  - katello-3.16-el8
  - katello-pulpcore-3.16-el7
  - katello-pulpcore-3.16-el8
  - katello-3.16-thirdparty-candlepin-rhel7
  - katello-candlepin-3.16-el8
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.16
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/2.1
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.22.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.5.3
    :repo: https://github.com/Katello/katello-host-tools.git
:ignores:
  - 28719 # Closed
  - 21508 # Fixed outside of Katello repo
  - 29435 # Fixed outside of Katello repo
  - 29449 # Fixed outside of Katello repo
  - 29436 # Fixed outside of Katello repo
  - 29340 # Closed
  - 28918 # Tracker
  - 28795 # Duplicate
  - 29603 # Fixed outside of Katello repo
  - 28968 # Tracker
:strict_keys: true
:gpg_key: B6F08CCF
:tags:
  - name: katello-3.16-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    build_target: katello-3.16-rhel7-build
    arches:
      - x86_64
  - name: katello-candlepin-3.16-el8
    based_off: katello-candlepin-nightly-el8
    build_target: katello-3.16-el8-build
    arches:
      - x86_64
  - name: katello-3.16-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.16-thirdparty-rhel7: null
      katello-3.16-rhel7-override: null
    build_target: katello-3.16-rhel7-build
    build_package_group_source_tag: katello-3.16-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.16-rhel7-build:
        katello-3.16-rhel7-override: 0
        foreman-plugins-2.1-rhel7: 3
        foreman-plugins-2.1-nonscl-rhel7: 4
        foreman-2.1-rhel7: 5
        foreman-2.1-nonscl-rhel7: 6
      katello-3.16-rhel7-override:
        katello-3.16-rhel7: 0
      katello-3.16-rhel7:
        katello-3.16-thirdparty-rhel7: 0
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
  - name: katello-3.16-el8
    based_off: katello-nightly-el8
    helper_tags:
      katello-3.16-thirdparty-el8: null
      katello-3.16-el8-override: null
    build_target: katello-3.16-el8-build
    build_package_group_source_tag: katello-3.16-el8-build
    arches:
      - x86_64
    inherits:
      katello-3.16-el8-build:
        katello-3.16-el8-override: 0
        foreman-plugins-2.1-el8: 3
        foreman-2.1-el8: 5
      katello-3.16-el8-override:
        katello-3.16-el8: 0
      katello-3.16-el8:
        katello-3.16-thirdparty-el8: 0
    external_repos:
      - test-flat-el8
      - centos8-devel
      - puppetlabs-puppet6-rhel-8
    build_groups:
      build:
        - bash
        - bzip2
        - centos-release
        - coreutils
        - cpio
        - diffutils
        - findutils
        - foreman-build
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - platform-python
        - python3-rpm-macros
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - centos-release
        - foreman-build
        - platform-python
        - python3-rpm-macros
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: katello-pulpcore-3.16-el7
    based_off: katello-pulpcore-nightly-el7
    helper_tags:
      katello-pulpcore-3.16-el7-override: null
    arches:
      - x86_64
    build_target: katello-pulpcore-3.16-el7-build
    inherits:
      katello-pulpcore-3.16-el7-build:
        katello-pulpcore-3.16-el7-override: 0
      katello-pulpcore-3.16-el7-override:
        katello-pulpcore-3.16-el7: 0
    external_repos:
      - centos7-os
      - centos7-updates
      - centos-sclo-rh-rhel-7
      - epel-7
    build_groups:
      build:
        - bash
        - bzip2
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - python3-rpm-macros
        - rh-postgresql12-scldevel
        - scl-utils-build
        - redhat-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils
  - name: katello-pulpcore-3.16-el8
    based_off: katello-pulpcore-nightly-el8
    helper_tags:
      katello-pulpcore-3.16-el8-override: null
    arches:
     - x86_64
    build_target: katello-pulpcore-3.16-el8-build
    inherits:
      katello-pulpcore-3.16-el8-build:
        katello-pulpcore-3.16-el8-override: 0
      katello-pulpcore-3.16-el8-override:
        katello-pulpcore-3.16-el8: 0
    external_repos:
    external_repos:
      - centos8-baseos
      - centos8-appstream
      - centos8-powertools
      - centos8-devel
    build_groups:
      build:
        - bash
        - bzip2
        - coreutils
        - cpio
        - diffutils
        - findutils
        - gawk
        - gcc
        - gcc-c++
        - grep
        - gzip
        - info
        - make
        - patch
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rpm-build
        - sed
        - shadow-utils
        - tar
        - unzip
        - util-linux
        - which
        - xz
      srpm-build:
        - bash
        - python3-rpm-macros
        - redhat-release
        - redhat-rpm-config
        - rhpkg-simple
        - rpm-build
        - shadow-utils

