---
:project: katello
:github_org: katello
:prior_releases:
  :3.8.0:
    :redmine_version_id: 356
  :3.7.0:
    :redmine_version_id: 264
  :3.7.1:
    :redmine_version_id: 355
:releases:
  :3.9.0:
    :redmine_version_id: 899
:code_name: New England IPA
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.9
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :katello-installer:
    :branch: KATELLO-3.9
    :repo: https://github.com/Katello/katello-installer.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/1.20
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 0.14.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.3.5
    :repo: https://github.com/Katello/katello-host-tools.git
  :bastion:
    :branch: 6.1.12
    :repo: https://github.com/Katello/bastion.git
:ignores:
:gpg_key: '10668686'
:mash_scripts:
 - katello-3.9-thirdparty-candlepin-rhel7
 - katello-3.9-rhel7
 - katello-3.9-client-rhel7
 - katello-3.9-client-rhel6
 - katello-3.9-client-rhel5
 - katello-3.9-client-fedora27
 - katello-3.9-client-fedora28
 - katello-3.9-client-sles11
 - katello-3.9-client-sles12
:tags:
  - name: katello-3.9-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.9-thirdparty-pulp-rhel7
    based_off: katello-thirdparty-pulp-rhel7
    arches:
      - x86_64
  - name: katello-3.9-thirdparty-pulp-rhel6
    based_off: katello-thirdparty-pulp-rhel6
    arches:
      - x86_64
  - name: katello-3.9-thirdparty-pulp-rhel5
    based_off: katello-thirdparty-pulp-rhel5
    arches:
      - x86_64
  - name: katello-3.9-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.9-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.9-rhel7-override: null
      katello-3.9-client-rhel7: null
    build_target: katello-3.9-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.9-rhel7-build:
        katello-3.9-rhel7-override: 0
        foreman-plugins-1.20-rhel7-override: 3
        foreman-1.20-nonscl-rhel7: 4
        foreman-1.20-rhel7: 10
      katello-3.9-rhel7-override:
        katello-3.9-rhel7: 0
      katello-3.9-rhel7:
        katello-3.9-thirdparty-rhel7: 0
      katello-3.9-client-rhel7:
        katello-3.9-rhel7: 0
        katello-3.9-thirdparty-pulp-rhel7: 2
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
      - foreman-rails-1.20-rhel-7
  - name: katello-3.9-rhel6
    based_off: katello-nightly-rhel6
    helper_tags:
      katello-3.9-thirdparty-rhel6: katello-thirdparty-rhel6
      katello-3.9-rhel6-override: null
      katello-3.9-client-rhel6: null
    build_target: katello-3.9-rhel6-build
    build_package_group_source_tag: katello-nightly-rhel6-build
    arches:
      - x86_64
    inherits:
      katello-3.9-rhel6-build:
        katello-3.9-rhel6-override: 0
      katello-3.9-rhel6-override:
        katello-3.9-rhel6: 1
      katello-3.9-rhel6:
        katello-3.9-thirdparty-rhel6: 0
      katello-3.9-client-rhel6:
        katello-3.9-rhel6: 0
        katello-3.9-thirdparty-pulp-rhel6: 2
    external_repos:
      - rhel-6.6-server
      - rhel-6.6-server-optional
      - epel-6
  - name: katello-3.9-rhel5
    based_off: katello-nightly-rhel6
    helper_tags:
      katello-3.9-rhel5-override: null
      katello-3.9-client-rhel5: null
    build_target: katello-3.9-rhel5-build
    build_package_group_source_tag: katello-nightly-rhel5-build
    arches:
      - x86_64
    inherits:
      katello-3.9-rhel5-build:
        katello-3.9-rhel5-override: 0
      katello-3.9-rhel5-override:
        katello-3.9-rhel5: 0
      katello-3.9-rhel5: {}
      katello-3.9-client-rhel5:
        katello-3.9-rhel5: 0
        katello-3.9-thirdparty-pulp-rhel5: 2
    external_repos:
      - rhel-5.9-server
      - epel-5
  - name: katello-3.9-fedora27
    based_off: katello-nightly-fedora27
    helper_tags:
      katello-3.9-client-fedora27: null
    build_target: katello-3.9-fedora27-build
    build_package_group_source_tag: katello-nightly-fedora27-build
    arches:
      - x86_64
    inherits:
      katello-3.9-fedora27-build:
        katello-3.9-fedora27: 0
      katello-3.9-fedora27: {}
      katello-3.9-client-fedora27:
        katello-3.9-fedora27: 0
    external_repos:
      - fedora-27-updates
      - fedora-27
  - name: katello-3.9-fedora28
    based_off: katello-nightly-fedora28
    helper_tags:
      katello-3.9-client-fedora28: null
    build_target: katello-3.9-fedora28-build
    build_package_group_source_tag: katello-nightly-fedora28-build
    arches:
      - x86_64
    inherits:
      katello-3.9-fedora28-build:
        katello-3.9-fedora28: 0
      katello-3.9-fedora28: {}
      katello-3.9-client-fedora28:
        katello-3.9-fedora28: 0
    external_repos:
      - fedora-28-updates
      - fedora-28
  - name: katello-3.9-sles12
    based_off: katello-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      katello-3.9-client-sles12: null
    inherits:
      katello-3.9-client-sles12:
        katello-3.9-sles12: 0
  - name: katello-3.9-sles11
    based_off: katello-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      katello-3.9-client-sles11: null
    inherits:
      katello-3.9-client-sles11:
        katello-3.9-sles11: 0

