---
:project: katello
:github_org: katello
:releases:
  :4.0.2:
    :redmine_version_id: 1433
  :4.0.1:
    :redmine_version_id: 1369
  :4.0.0:
    :redmine_version_id: 1177
:prior_releases:
  :3.17.3:
    :redmine_version_id: 1365
  :3.18.2:
    :redmine_version_id: 1353
  :3.18.2.1:
    :redmine_version_id: 1384
  :3.18.3:
    :redmine_version_id: 1370
  :3.18.4:
    :redmine_version_id: 1396
:code_name:
:mash_scripts:
  - katello-4.0-rhel7
  - katello-4.0-thirdparty-candlepin-rhel7
  - katello-4.0-el8
  - katello-candlepin-4.0-el8
:repos:
  :katello:
    :main: true
    :branch: KATELLO-4.0
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/2.4
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 1.0.0
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.5.4
    :repo: https://github.com/Katello/katello-host-tools.git
  :katello-certs-tools:
    :branch: 2.7.3
    :repo: https://github.com/Katello/katello-certs-tools.git
  :foreman_virt_who_configure:
    :branch: 0.5.5
    :repo: https://github.com/theforeman/foreman_virt_who_configure.git
:ignores:
  - 31308 # already in
  - 31712 # not merged into 2.4-stable
  - 31967 # for katello 3.18
  - 31636 # migration fixes for katello 3.18
  - 31902 # for katello 3.17, 3.18
  - 31974 # for katello 3.18
  - 32060 # for katello 3.18
  - 32062 # for katello 3.18
  - 32066 # for migration/3.18
  - 32058 # for migration/3.18
  - 32109 # for migraiton/3.18
  - 32210 # for migration/3.18
  - 32226 # for migration/3.18
  - 32301 # for migration/3.18
  - 32302 # for migration/3.18
  - 32420 # for migration/3.18
  - 32256 # for migration/3.18
  - 32449 # for migration/3.18
  - 32472 # for migration/3.18
  - 32663 # for migration/3.18
  - 32831 # for migration/3.18
  - 32869 # for migration/3.18
  - 32786 # for migration/3.18
  - 32887 # for migration/3.18
  - 32888 # for migration/3.18

:strict_keys: true
:gpg_key: AC2AD9F1
:tags:
  - name: katello-4.0-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    build_target: katello-4.0-rhel7-build
    arches:
      - x86_64
  - name: katello-candlepin-4.0-el8
    based_off: katello-candlepin-nightly-el8
    build_target: katello-4.0-el8-build
    arches:
      - x86_64
  - name: katello-4.0-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-4.0-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-4.0-rhel7-override: null
    build_target: katello-4.0-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-4.0-rhel7-build:
        katello-4.0-rhel7-override: 0
        foreman-plugins-2.4-rhel7-override: 3
        foreman-2.4-rhel7: 10
      katello-4.0-rhel7-override:
        katello-4.0-rhel7: 0
      katello-4.0-rhel7:
        katello-4.0-thirdparty-rhel7: 0
        foreman-2.4-nonscl-rhel7: 1
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
  - name: katello-4.0-el8
    based_off: katello-nightly-el8
    helper_tags:
      katello-thirdparty-el8: null
      katello-4.0-el8-override: null
    build_target: katello-4.0-el8-build
    build_package_group_source_tag: katello-nightly-el8-build
    arches:
      - x86_64
    inherits:
      katello-4.0-el8-build:
        katello-4.0-el8-override: 0
        foreman-plugins-2.4-el8: 3
        foreman-2.4-el8: 5
      katello-4.0-el8-override:
        katello-4.0-el8: 0
      katello-4.0-el8:
        katello-thirdparty-el8: 0
    external_repos:
      - test-flat-el8
      - centos8-devel
      - puppetlabs-puppet6-rhel-8
