---
:project: katello
:github_org: katello
:releases:
  :4.3.0:
    :redmine_version_id: 1473
:prior_releases:
  :4.2.0:
    :redmine_version_id: 1383
  :4.1.3:
    :redmine_version_id: 1474
  :4.0.3:
    :redmine_version_id: 1479    
:code_name: Ghost Pepper
:mash_scripts:
  - katello-4.3-rhel7
  - katello-4.3-thirdparty-candlepin-rhel7
  - katello-4.3-el8
  - katello-candlepin-4.3-el8
:repos:
  :katello:
    :main: true
    :branch: KATELLO-4.3
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :foreman-packaging:
    :branch: rpm/3.1
    :repo: https://github.com/theforeman/foreman-packaging.git
  :hammer-cli-katello:
    :branch: 1.3.z
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-host-tools:
    :branch: 3.5.7
    :repo: https://github.com/Katello/katello-host-tools.git
  :katello-certs-tools:
    :branch: 2.8.1
    :repo: https://github.com/Katello/katello-certs-tools.git
  :foreman_virt_who_configure:
    :branch: 0.5.8
    :repo: https://github.com/theforeman/foreman_virt_who_configure.git
  :smart_proxy_container_gateway:
    :branch: 1.0.6
    :repo: https://github.com/Katello/smart_proxy_container_gateway.git
  :katello-selinux:
    :branch: 4.0.2
    :repo: https://github.com/Katello/katello-selinux.git
:ignores:
:strict_keys: true
:gpg_key: 1434F5D3
:tags:
  - name: katello-4.3-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    build_target: katello-4.3-rhel7-build
    arches:
      - x86_64
  - name: katello-candlepin-4.3-el8
    based_off: katello-candlepin-nightly-el8
    build_target: katello-4.3-el8-build
    arches:
      - x86_64
  - name: katello-4.3-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-4.3-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-4.3-rhel7-override: null
    build_target: katello-4.3-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-4.3-rhel7-build:
        katello-4.3-rhel7-override: 0
        foreman-plugins-3.0-rhel7-override: 3
        foreman-3.0-rhel7: 10
      katello-4.3-rhel7-override:
        katello-4.3-rhel7: 0
      katello-4.3-rhel7:
        katello-4.3-thirdparty-rhel7: 0
        foreman-3.0-nonscl-rhel7: 1
    external_repos:
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-7-server-updates
      - centos-7-server
  - name: katello-4.3-el8
    based_off: katello-nightly-el8
    helper_tags:
      katello-thirdparty-el8: null
      katello-4.3-el8-override: null
    build_target: katello-4.3-el8-build
    build_package_group_source_tag: katello-nightly-el8-build
    arches:
      - x86_64
    inherits:
      katello-4.3-el8-build:
        katello-4.3-el8-override: 0
        foreman-plugins-3.0-el8: 3
        foreman-3.0-el8: 5
      katello-4.3-el8-override:
        katello-4.3-el8: 0
      katello-4.3-el8:
        katello-4.3-thirdparty-el8: 0
    external_repos:
      - flat-ruby27-el8
      - test-flat-el8
      - centos8-devel
      - puppetlabs-puppet6-rhel-8
