---
:project: katello
:github_org: katello
:prior_releases:
  :3.6.0:
    :redmine_release_id: 284
  :3.6.1:
    :redmine_release_id: 352
  :3.5.2:
    :redmine_release_id: 339
:releases:
  :3.7.0:
    :redmine_release_id: 338
:code_name: Blonde Ale
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.7
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :katello-selinux:
    :branch: 3.0.3
    :repo: https://github.com/Katello/katello-selinux.git
  :katello-installer:
    :branch: KATELLO-3.7
    :repo: https://github.com/Katello/katello-installer.git
    :version_branch: true
  :hammer-cli-katello:
    :branch: 0.12.1
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :foreman-packaging:
    :branch: rpm/1.18
    :repo: https://github.com/theforeman/foreman-packaging.git
  :katello-host-tools:
    :branch: 3.2.1
    :repo: https://github.com/Katello/katello-host-tools.git
  :bastion:
    :branch: 6.1.11
    :repo: https://github.com/Katello/bastion
  :puppet-pulp:
    :branch: 5.4.1
    :repo: https://github.com/Katello/puppet-pulp
  :puppet-foreman_proxy_content:
    :branch: 7.1.0
    :repo: https://github.com/Katello/puppet-foreman_proxy_content
  :puppet-katello:
    :branch: 8.0.1
    :repo: https://github.com/Katello/puppet-katello
  :puppet-candlepin:
    :branch: 5.1.0
    :repo: https://github.com/Katello/puppet-candlepin
  :puppet-certs:
    :branch: 4.1.0
    :repo: https://github.com/Katello/puppet-certs

:gpg_key: '4D0D8597'
:mash_scripts:
 - katello-3.7-thirdparty-candlepin-rhel7
 - katello-3.7-rhel7
 - katello-3.7-client-rhel7
 - katello-3.7-client-rhel6
 - katello-3.7-client-rhel5
 - katello-3.7-client-fedora26
 - katello-3.7-client-fedora27
:tags:
  - name: katello-3.7-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.7-thirdparty-pulp-rhel7
    based_off: katello-thirdparty-pulp-rhel7
    arches:
      - x86_64
  - name: katello-3.7-thirdparty-pulp-rhel6
    based_off: katello-thirdparty-pulp-rhel6
    arches:
      - x86_64
  - name: katello-3.7-thirdparty-pulp-rhel5
    based_off: katello-thirdparty-pulp-rhel5
    arches:
      - x86_64
  - name: katello-3.7-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.7-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.7-rhel7-override: null
      katello-3.7-client-rhel7: null
    build_target: katello-3.7-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.7-rhel7-build:
        katello-3.7-rhel7-override: 0
        foreman-plugins-1.18-rhel7-override: 3
        foreman-1.18-nonscl-rhel7: 4
        foreman-1.18-rhel7: 10
      katello-3.7-rhel7-override:
        katello-3.7-rhel7: 0
      katello-3.7-rhel7:
        katello-3.7-thirdparty-rhel7: 0
      katello-3.7-client-rhel7:
        katello-3.7-rhel7: 0
        katello-3.7-thirdparty-pulp-rhel7: 2
    external_repos:
      - rhel-7.0-server
      - rhel-7.0-server-optional
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-sclo-sclo-rhel-7
      - tfm-ror51-rhel-7
      - centos-7-server
  - name: katello-3.7-rhel6
    based_off: katello-3.7-nightly-rhel6
    helper_tags:
      katello-3.7-thirdparty-rhel6: katello-thirdparty-rhel6
      katello-3.7-rhel6-override: null
      katello-3.7-client-rhel6: null
    build_target: katello-3.7-rhel6-build
    build_package_group_source_tag: katello-nightly-rhel6-build
    arches:
      - x86_64
    inherits:
      katello-3.7-rhel6-build:
        katello-3.7-rhel6-override: 0
      katello-3.7-rhel6-override:
        katello-3.7-rhel6: 1
      katello-3.7-rhel6:
        katello-3.7-thirdparty-rhel6: 0
      katello-3.7-client-rhel6:
        katello-3.7-rhel6: 0
        katello-3.7-thirdparty-pulp-rhel6: 2
    external_repos:
      - rhel-6.6-server
      - rhel-6.6-server-optional
      - epel-6
  - name: katello-3.7-rhel5
    based_off: katello-nightly-rhel6
    helper_tags:
      katello-3.7-rhel5-override: null
      katello-3.7-client-rhel5: null
    build_target: katello-3.7-rhel5-build
    build_package_group_source_tag: katello-nightly-rhel5-build
    arches:
      - x86_64
    inherits:
      katello-3.7-rhel5-build:
        katello-3.7-rhel5-override: 0
      katello-3.7-rhel5-override:
        katello-3.7-rhel5: 0
      katello-3.7-rhel5: {}
      katello-3.7-client-rhel5:
        katello-3.7-rhel5: 0
        katello-3.7-thirdparty-pulp-rhel5: 2
    external_repos:
      - rhel-5.9-server
      - epel-5
  - name: katello-3.7-fedora26
    based_off: katello-nightly-fedora26
    helper_tags:
      katello-3.7-client-fedora26: null
    build_target: katello-3.7-fedora26-build
    build_package_group_source_tag: katello-nightly-fedora26-build
    arches:
      - x86_64
    inherits:
      katello-3.7-fedora26-build:
        katello-3.7-fedora26: 0
      katello-3.7-fedora26: {}
      katello-3.7-client-fedora26:
        katello-3.7-fedora26: 0
    external_repos:
      - fedora-26-updates
      - fedora-26
  - name: katello-3.7-fedora27
    based_off: katello-nightly-fedora27
    helper_tags:
      katello-3.7-client-fedora27: null
    build_target: katello-3.7-fedora27-build
    build_package_group_source_tag: katello-nightly-fedora27-build
    arches:
      - x86_64
    inherits:
      katello-3.7-fedora27-build:
        katello-3.7-fedora27: 0
      katello-3.7-fedora27: {}
      katello-3.7-client-fedora27:
        katello-3.7-fedora27: 0
    external_repos:
      - fedora-27-updates
      - fedora-27
  - name: katello-3.7-sles12
    based_off: katello-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      katello-3.7-client-sles12: null
    inherits:
      katello-3.7-client-sles12:
        katello-3.7-sles12: 0
  - name: katello-3.7-sles11
    based_off: katello-nightly-sles12
    arches:
      - x86_64
    helper_tags:
      katello-3.7-client-sles11: null
    inherits:
      katello-3.7-client-sles11:
        katello-3.7-sles11: 0
