---
:project: katello
:github_org: katello
:prior_releases:
  :3.4.5:
    :redmine_release_id: 258
  :3.4.6:
    :redmine_release_id: 295
:releases:
  :3.5.0:
    :redmine_release_id: 250
:code_name: Schwarzbier
:repos:
  :katello:
    :main: true
    :branch: KATELLO-3.5
    :repo: https://github.com/Katello/katello.git
    :version_branch: true
  :katello-selinux:
    :branch: 3.0.3
    :repo: https://github.com/Katello/katello-selinux.git
  :katello-installer:
    :branch: KATELLO-3.5
    :repo: https://github.com/Katello/katello-installer.git
    :version_branch: true
  :hammer-cli-katello:
    :branch: 0.11.2
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello-packaging:
    :branch: KATELLO-3.5
    :repo: https://github.com/Katello/katello-packaging.git
    :version_branch: true
  :katello-agent:
    :branch: 3.1.0
    :repo: https://github.com/Katello/katello-agent.git
  :bastion:
    :branch: 6.1.0
    :repo: https://github.com/Katello/bastion
  :puppet-pulp:
    :branch: 5.1.0
    :repo: https://github.com/Katello/puppet-pulp
  :puppet-foreman_proxy_content:
    :branch: 6.0.0
    :repo: https://github.com/Katello/puppet-foreman_proxy_content
  :puppet-katello:
    :branch: 7.0.0
    :repo: https://github.com/Katello/puppet-katello
  :puppet-candlepin:
    :branch: 4.0.0
    :repo: https://github.com/Katello/puppet-candlepin
  :puppet-certs:
    :branch: 3.0.0
    :repo: https://github.com/Katello/puppet-certs

:ignores:
:gpg_key: '3DA3BBF0'
:mash_scripts:
 - katello-3.5-thirdparty-candlepin-rhel7
 - katello-3.5-thirdparty-pulp-rhel7
 - katello-3.5-rhel7
 - katello-3.5-client-rhel7
 - katello-3.5-client-rhel6
 - katello-3.5-client-rhel5
 - katello-3.5-client-fedora25
 - katello-3.5-client-fedora26
:tags:
  - name: katello-3.5-thirdparty-candlepin-rhel7
    based_off: katello-thirdparty-candlepin-rhel7
    arches:
      - x86_64
  - name: katello-3.5-thirdparty-pulp-rhel7
    based_off: katello-thirdparty-pulp-rhel7
    arches:
      - x86_64
  - name: katello-3.5-thirdparty-pulp-rhel6
    based_off: katello-thirdparty-pulp-rhel6
    arches:
      - x86_64
  - name: katello-3.5-thirdparty-pulp-rhel5
    based_off: katello-thirdparty-pulp-rhel5
    arches:
      - x86_64
  - name: katello-3.5-rhel7
    based_off: katello-nightly-rhel7
    helper_tags:
      katello-3.5-thirdparty-rhel7: katello-thirdparty-rhel7
      katello-3.5-rhel7-override: null
      katello-3.5-client-rhel7: null
    build_target: katello-3.5-rhel7-build
    build_package_group_source_tag: katello-nightly-rhel7-build
    arches:
      - x86_64
    inherits:
      katello-3.5-rhel7-build:
        katello-3.5-rhel7-override: 0
        foreman-plugins-1.15-rhel7-override: 3
        foreman-1.15-nonscl-rhel7: 4
        foreman-1.15-rhel7: 10
      katello-3.5-rhel7-override:
        katello-3.5-rhel7: 0
      katello-3.5-rhel7:
        katello-3.5-thirdparty-rhel7: 0
      katello-3.5-client-rhel7:
        katello-3.5-rhel7: 0
        katello-3.5-thirdparty-pulp-rhel7: 2
    :external_repos:
      - rhel-7.0-server
      - rhel-7.0-server-optional
      - epel-7
      - centos-sclo-rh-rhel-7
      - centos-sclo-sclo-rhel-7
  - name: katello-3.5-rhel6
    based_off: katello-nightly-rhel6
    helper_tags:
      katello-3.5-thirdparty-rhel6: katello-thirdparty-rhel6
      katello-3.5-rhel6-override: null
      katello-3.5-client-rhel6: null
    build_target: katello-3.5-rhel6-build
    build_package_group_source_tag: katello-nightly-rhel6-build
    arches:
      - x86_64
    inherits:
      katello-3.5-rhel6-build:
        katello-3.5-rhel6-override: 0
      katello-3.5-rhel6-override:
        katello-3.5-rhel6: 1
      katello-3.5-rhel6:
        katello-3.5-thirdparty-rhel6: 0
      katello-3.5-client-rhel6:
        katello-3.5-rhel6: 0
        katello-3.5-thirdparty-pulp-rhel6: 2
    external_repos:
      - rhel-6.6-server
      - rhel-6.6-server-optional
      - epel-6
  - name: katello-3.5-rhel5
    based_off: katello-nightly-rhel5
    helper_tags:
      katello-3.5-rhel5-override: null
      katello-3.5-client-rhel5: null
    build_target: katello-3.5-rhel5-build
    build_package_group_source_tag: katello-nightly-rhel5-build
    arches:
      - x86_64
    inherits:
      katello-3.5-rhel5-build:
        katello-3.5-rhel5-override: 0
      katello-3.5-rhel5-override:
        katello-3.5-rhel5: 0
      katello-3.5-rhel5: {}
      katello-3.5-client-rhel5:
        katello-3.5-rhel5: 0
        katello-3.5-thirdparty-pulp-rhel5: 2
    :external_repos:
      - rhel-5.9-server
      - epel-5
  - name: katello-3.5-fedora25
    based_off: katello-nightly-fedora25
    helper_tags:
      katello-3.5-client-fedora25: null
    build_target: katello-3.5-fedora25-build
    build_package_group_source_tag: katello-nightly-fedora25-build
    arches:
      - x86_64
    inherits:
      katello-3.5-fedora25-build:
        katello-3.5-fedora25: 0
      katello-3.5-fedora25: {}
      katello-3.5-client-fedora25:
        katello-3.5-fedora25: 0
    external_repos:
      - fedora-25-updates
      - fedora-25
  - name: katello-3.5-fedora26
    based_off: katello-nightly-fedora26
    helper_tags:
      katello-3.5-client-fedora26: null
    build_target: katello-3.5-fedora26-build
    build_package_group_source_tag: katello-nightly-fedora26-build
    arches:
      - x86_64
    inherits:
      katello-3.5-fedora26-build:
        katello-3.5-fedora26: 0
      katello-3.5-fedora26: {}
      katello-3.5-client-fedora26:
        katello-3.5-fedora26: 0
    external_repos:
      - fedora-26-updates
      - fedora-26
