---
:project: foreman
:github_org: theforeman
:prior_releases:
  :1.14.0:
    :redmine_version_id: 199
  :1.14.1:
    :redmine_version_id: 197
  :1.14.2:
    :redmine_version_id: 201
  :1.14.3:
    :redmine_version_id: 203
  :1.14.4:
    :redmine_version_id: 511
:releases:
  :1.15.4:
    :redmine_version_id: 148
  :1.15.3:
    :redmine_version_id: 144
  :1.15.2:
    :redmine_version_id: 146
  :1.15.1:
    :redmine_version_id: 143
  :1.15.0:
    :redmine_version_id: 36
:repos:
  :foreman:
    :main: true
    :branch: 1.15-stable
    :repo: https://github.com/theforeman/foreman.git
  :smart-proxy:
    :main: true
    :branch: 1.15-stable
    :repo: https://github.com/theforeman/smart-proxy.git
  :foreman-selinux:
    :main: true
    :branch: 1.15-stable
    :repo: https://github.com/theforeman/foreman-selinux.git
  :foreman-installer:
    :main: true
    :branch: 1.15-stable
    :repo: https://github.com/theforeman/foreman-installer.git
  :foreman-packaging-deb:
    :main: true
    :branch: deb/1.15
    :repo: https://github.com/theforeman/foreman-packaging.git
  :foreman-packaging-rpm:
    :main: true
    :branch: rpm/1.15
    :repo: https://github.com/theforeman/foreman-packaging.git
  :community-templates:
    :main: true
    :branch: 1.15-stable
    :repo: https://github.com/theforeman/community-templates.git
